name: "🐛 Hata Bildirimi"
description: Yeni bir hata için ticket oluştur
title: "🐛 [BUG] - <başlık>"
labels:
  - "bug"
body:
  - type: textarea
    id: description
    attributes:
      label: "Açıklama"
      description: Karşılaştığınız hatayı net ve kısa şekilde yazın
      placeholder: Olayın kısa ve net açıklaması...
    validations:
      required: true

  - type: input
    id: reprod-url
    attributes:
      label: "Tekrarlama URL'si"
      description: Hatanın tekrarlandığı GitHub repo veya canlı linki
      placeholder: "örn. https://github.com/KULLANICI/REPO-ADI"
    validations:
      required: true

  - type: textarea
    id: reprod
    attributes:
      label: "Tekrarlama Adımları"
      description: Hatanın oluşması için izlenen adımlar
      value: |
        1. ... sayfasına git
        2. ... butonuna tıkla
        3. ... yap
        4. Hata görülür
      render: bash
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: "Ekran Görüntüsü"
      description: Varsa ekran görüntüsü ekleyin
      value: |
        ![AÇIKLAMA](LINK.png)
      render: bash
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: "Log Çıktıları"
      description: İlgili log çıktılarını buraya yapıştırın. Otomatik olarak kod blokları halinde biçimlendirilecektir.
      render: bash
    validations:
      required: false
 
 
