name: "💡 Özellik Talebi"
description: Yeni bir özellik/iyileştirme talebi oluştur
title: "💡 [FEATURE] - <başlık>"
labels:
  - "enhancement"

body:
  - type: input
    id: module
    attributes:
      label: "Modül"
      description: Hangi modül için? (örn. coverage, efatura, stok)
      placeholder: "coverage"
    validations:
      required: true

  - type: dropdown
    id: stage
    attributes:
      label: "Aşama"
      description: 3 aşamalı akışınıza göre seçin
      options:
        - Genel Analiz
        - Teknik Analiz
        - Kodlama
      default: 0

  - type: dropdown
    id: priority
    attributes:
      label: "Öncelik"
      options:
        - Kritik
        - Yüksek
        - Orta
        - Düşük
      default: 2
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: "Özet"
      description: Özellik isteğinin kısa açıklaması
      placeholder: Birkaç cümlede ihtiyacı ve hedefi anlatın
    validations:
      required: true

  - type: textarea
    id: gwt
    attributes:
      label: "Kabul Kriterleri (Given / When / Then)"
      description: Net kabul kriterleri yazın (test edilebilir)
      placeholder: |
        Given ...
        When  ...
        Then  ...
    validations:
      required: true

  - type: textarea
    id: basic_example
    attributes:
      label: "Temel Örnek / Kullanım"
      description: Beklenen davranışa dair kısa örnekler
      placeholder: |
        - Kullanıcı ... yaptığında ... görür
        - API ... parametreleriyle çağrıldığında ... döner
    validations:
      required: true

  - type: textarea
    id: drawbacks
    attributes:
      label: "Etkiler / Sakıncalar"
      description: Performans, güvenlik, bakım maliyeti vb. etkiler
      placeholder: Tarafsız şekilde olası riskleri belirtin
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: "Referanslar"
      description: İlgili PR/Issue/Doc bağlantıları
      placeholder: |
        - #123
        - /docs/<modul>/02_teknik_analiz.md
        - Dış linkler
    validations:
      required: false
