name: "💡 Özellik Talebi"
description: Yeni bir özellik talebi için ticket oluştur
title: "💡 [REQUEST] - <başlık>"
labels:
  - "question"
body:
  - type: input
    id: start_date
    attributes:
      label: "Başlangıç Tarihi"
      description: Geliştirmenin başlangıç tarihi
      placeholder: "ay/gün/yıl"
    validations:
      required: false

  - type: textarea
    id: implementation_pr
    attributes:
      label: "Uygulama PR"
      description: Kullanılan pull request
      placeholder: "#Pull Request ID"
    validations:
      required: false

  - type: textarea
    id: reference_issues
    attributes:
      label: "Referans Issue'lar"
      description: İlgili/ortak issue'lar
      placeholder: "#Issue ID'leri"
    validations:
      required: false

  - type: textarea
    id: summary
    attributes:
      label: "Özet"
      description: Özelliğin kısa açıklaması
      placeholder: Özellik talebinizi birkaç cümlede anlatın
    validations:
      required: true

  - type: textarea
    id: basic_example
    attributes:
      label: "Basit Örnek"
      description: Özelliğinizin temel kullanım örnekleri
      placeholder: Özelliğe dair birkaç somut örnek yazın
    validations:
      required: true

  - type: textarea
    id: drawbacks
    attributes:
      label: "Sakıncalar"
      description: Özellik talebinizin olası sakıncaları/etkileri nelerdir?
      placeholder: Tarafsız kalarak sakıncaları ve etkileri belirtin
    validations:
      required: true

  - type: textarea
    id: unresolved_question
    attributes:
      label: "Cevapsız Sorular"
      description: Hâlâ netleşmeyen sorular nelerdir?
      placeholder: Netleşmemiş başlıkları buraya yazın
    validations:
      required: false
